name: binder-remi
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - python=3.7
  - pip
  - pip:
    - GitPython
    - pathtools
    - remi
    - streamlit
    - jupyter-server-proxy 
    - nbserverproxy
